[mssql]
server = "B2B00016\\SQLEXPRESS"
database = "AdventureWorks2019"
driver = "{ODBC Driver 17 for SQL Server}"
trusted_connection = "yes"

[postgres]
username = "postgres"
password = "2512"
host = "localhost"
port = "5432"
database = "AdventureDB"
schema = "stg"
